### ISSUE TITLE
Make sure on checkbox questions the points calculate SUM of all questions checked, not just points for the MAX answer chosen.

### ISSUE THREAD

**Issue by websiddu** [websiddu/green#12]

**Comment by websiddu** [comment]
Should this be the sum of all the points 

[x] Option 1 – 5pts 
[x] Option 2 – 3pts 
[ ] Option 3 – 10pts 

Should this be 5 + 3 = 8 points out of 18 possible points ?

**Comment by daimoneklund** [comment]
Yes, the logic you mentioned is correct. The possible points should also be SUM of all points for checkbox questions, not just MAX.

**Comment by websiddu** [comment]
But what should be the possible points for the this question is that also sum ?

**Comment by websiddu** [comment]
Done :)

**Comment by daimoneklund** [comment]
I think you did this, but to clarify - the possible points for the question is also sum of possible points for all answers.

**Comment by websiddu** [comment]
Yeah done :)
