### ISSUE TITLE
Fix user save as draft button

### ISSUE THREAD

**Issue by daimoneklund** [websiddu/green#23]
As a user, entering a form and clicking "save as draft" shows the message "Changes must be saved!" above the button, even after saving and no changes were made.
If there are unsaved changes, we don't need to show a message. When a user clicks save as draft, show  a message "Entries saved"

Also, saving as draft then grays out the save as draft button so it can not be selected. However, making further changes to the same section does not change the button status, so if I save as draft, then make changes on the same screen I can not save the updates as a draft.

**Comment by websiddu** [comment]
Done :)
