### ISSUE TITLE
Show certificate preview

### ISSUE THREAD

**Issue by daimoneklund** [websiddu/green#26]
When an editor is creating a certificate, we should have a "preview" button so they can see what the certificate will look like (and make it easier for them to know how to enter text, etc.)

**Comment by websiddu** [comment]
Here is the screenshot :) 

![screen shot 2015-04-23 at 10 34 44 am](https://cloud.githubusercontent.com/assets/968912/7303288/6d54b5fa-e9a4-11e4-9a30-f655df05b3b6.png)
