### ISSUE TITLE
Fix conditional scoring logic

### ISSUE THREAD

**Issue by daimoneklund** [websiddu/green#34]
If a question is conditional, the points for that question should not be included in the total points unless the condition is met. 

For example, if I have three questions:
1. Do you recycle?   Yes: 1 point, No: 0 point, N/A (not applicable question): 0 point
2. (conditional on answer of "yes" or "no" to the first question)- Do you recycle everything? Yes 1 point, No: 0 point

3: Do you have a compost bin? Yes: 1 point, No: 0 point

At first user will see question 1 and 3, and there will be 2 possible points. If user answers yes or no to question 1, then user sees question 2 and there are now 3 possible points. 

If user answers N/A to question 1, then it is not applicable and question 2 will not be triggered, so possible points are now 1.

**Comment by websiddu** [comment]
Hi @daimoneklund, This is taking lot more time then I though. As I have to change the scoring logic completely.. I am almost rewriting the whole scoring code.. I will complete this ASAP.
