### ISSUE TITLE
Anchor Links

### ISSUE THREAD

**Issue by crtoman** [websiddu/green#45]
All of the "How To..." or "More Information" links go to the top of the Green Labs Certification Resources web page, which is extremely repetitive and inefficient for finding answers to any questions - I realize there are issues with the anchor links on the web page, but it would be great if this could be resolved or worked around (potentially by creating new web pages for each section).

**Comment by daimoneklund** [comment]
We'll take care of this on the green.uw.edu webpage by creating new pages - not an issue with the certification.
