### ISSUE TITLE
Add Link to Mercury Thermometer Swap Program

### ISSUE THREAD

**Issue by crtoman** [websiddu/green#48]
Question C4 mentions a 'Mercury Thermometer Swap Program,' but does not include a link. Would like to add one for labs that have not heard or are not aware of program.

Link: https://www.ehs.washington.edu/eporecycle/hg.shtm

**Comment by daimoneklund** [comment]
Chris - for stuff like links/content, I'll show you how to add. GitHub is for issues with the programming.
